# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 07:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_loc', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('tip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('code', models.IntegerField(default=orders.models.generate_code)),
                ('timeliness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('friendliness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('responsetime', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text_feedback', models.CharField(blank=True, max_length=140, null=True)),
                ('delivers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to=settings.AUTH_USER_MODEL)),
                ('initiates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiates', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Item')),
            ],
        ),
    ]
